import type { CompletionContract } from "./types.js";

export const sampleContract: CompletionContract = {
  schemaVersion: "1.0",
  id: "checkout-v42-completion",
  goal: "Release checkout v42 without a functional or operational regression.",
  executor: "release-agent",
  actors: [
    { id: "release-agent", label: "Release Agent", type: "agent" },
    { id: "ci-verifier", label: "CI Verifier", type: "service" },
    {
      id: "synthetic-monitor",
      label: "Synthetic Monitor",
      type: "service",
    },
    { id: "release-manager", label: "Release Manager", type: "human" },
  ],
  criteria: [
    {
      id: "tests-pass",
      statement: "The checkout test suite passes, including the rejected-card path.",
      critical: true,
      minPassing: 2,
      maxAgeMinutes: 60,
      independentVerifier: true,
      requiredEvidenceTypes: ["test", "review"],
      requiredTags: ["commit:v42"],
      negativeTestRequired: true,
    },
    {
      id: "service-healthy",
      statement: "Checkout remains healthy under a staging synthetic transaction.",
      critical: true,
      minPassing: 2,
      maxAgeMinutes: 30,
      independentVerifier: true,
      requiredEvidenceTypes: ["metric", "observation"],
      requiredTags: ["staging"],
    },
    {
      id: "runbook-linked",
      statement: "The release references the current rollback runbook.",
      critical: false,
      minPassing: 1,
      maxAgeMinutes: 1_440,
      independentVerifier: false,
      requiredEvidenceTypes: ["artifact"],
    },
  ],
  evidence: [
    {
      id: "ev-ci-tests",
      criterionId: "tests-pass",
      type: "test",
      producedBy: "release-agent",
      verifiedBy: "ci-verifier",
      capturedAt: "2026-07-29T04:12:00.000Z",
      outcome: "pass",
      artifactRef: "https://ci.example/runs/4102",
      digest: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      tags: ["commit:v42", "negative"],
      details: "1,284 tests passed, including rejected-card assertions.",
    },
    {
      id: "ev-release-review",
      criterionId: "tests-pass",
      type: "review",
      producedBy: "release-agent",
      verifiedBy: "release-manager",
      capturedAt: "2026-07-29T04:19:00.000Z",
      outcome: "pass",
      artifactRef: "https://reviews.example/releases/v42",
      digest: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      tags: ["commit:v42"],
      details: "Release manager reviewed the test report and failure-path coverage.",
    },
    {
      id: "ev-latency-metric",
      criterionId: "service-healthy",
      type: "metric",
      producedBy: "release-agent",
      verifiedBy: "synthetic-monitor",
      capturedAt: "2026-07-29T04:22:00.000Z",
      outcome: "pass",
      artifactRef: "https://metrics.example/checkout/v42",
      digest: "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
      tags: ["staging"],
      details: "P95 checkout latency remained below the 450 ms budget.",
    },
    {
      id: "ev-staging-observation",
      criterionId: "service-healthy",
      type: "observation",
      producedBy: "synthetic-monitor",
      verifiedBy: "release-manager",
      capturedAt: "2026-07-29T04:25:00.000Z",
      outcome: "pass",
      artifactRef: "https://synthetics.example/checks/927",
      digest: "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
      tags: ["staging"],
      details: "A complete staging purchase succeeded and emitted the expected events.",
    },
    {
      id: "ev-runbook",
      criterionId: "runbook-linked",
      type: "artifact",
      producedBy: "release-agent",
      verifiedBy: "release-agent",
      capturedAt: "2026-07-29T03:55:00.000Z",
      outcome: "pass",
      artifactRef: "https://docs.example/runbooks/checkout-rollback",
      digest: "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      tags: ["runbook"],
      details: "Release metadata links the versioned rollback runbook.",
    },
  ],
};
